### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sampahcokk-dev** [kshubham506/vcplayerbot#13]
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)

**Comment by kshubham506** [comment]
Can you attach the stack trace ?

**Comment by Sampahcokk-dev** [comment]
python3 main.py -env prod
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from extras.dbhandler import handle_db_calls
  File "/home/runner/tesbotMusik/vcplayerbot/extras/__init__.py", line 1, in <module>
    from extras.callmanager import MusicPlayer
  File "/home/runner/tesbotMusik/vcplayerbot/extras/callmanager.py", line 1, in <module>
    from utils import VideoFetchFromId
  File "/home/runner/tesbotMusik/vcplayerbot/utils/__init__.py", line 1, in <module>
    import asyncio
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)

**Comment by Sampahcokk-dev** [comment]
i run this in replit
